import { PricingPlan } from "@/types/content";

export const pricingPlans: PricingPlan[] = [
  {
    id: "starter-audit",
    name: "AI Readiness Denetimi",
    badge: "Başlangıç",
    price: "₺7.500",
    period: "tek seferlik",
    description: "İşletmenizin yapay zeka çağına ne kadar hazır olduğunu ölçen kapsamlı teşhis paketi.",
    isPopular: false,
    features: [
      "Kapsamlı AI Olgunluk Skoru (0-100)",
      "Web Sitesi ve AEO (AI Motoru) Analizi",
      "Müşteri İletişimi Açık Teşhis Raporu",
      "Geçici Dijital İnceleme Raporu",
      "E-posta ile Teknik İyileştirme Rehberi",
    ],
    ctaText: "Denetimi Başlat",
    ctaHref: "#dogrulama",
  },
  {
    id: "verified-business",
    name: "AI READY Rozeti & Sertifika",
    badge: "En Çok Tercih Edilen",
    price: "₺16.000",
    period: "yıllık lisans",
    description: "Resmi AI READY BUSINESS rozeti, 7/24 AI sorgulama altyapısı ve tam doğrulanmış sertifika.",
    isPopular: true,
    features: [
      "Tüm Başlangıç Denetim Raporları",
      "5 Yıldızlı 'AI READY BUSINESS' 3D/2D Rozeti",
      "aireadybusiness.ai Resmi Doğrulama Sayfası",
      "Web Sitesi için Dinamik Rozet Widget Kodu",
      "ChatGPT & Perplexity LLM İndeks Kaydı",
      "7/24 AI İletişim Entegrasyon Desteği",
      "Yıllık Yenileme ve Sürekli AI Denetimi",
    ],
    ctaText: "Hemen Sertifikanızı Alın",
    ctaHref: "#dogrulama",
  },
  {
    id: "enterprise-full",
    name: "Kurumsal AI Dönüşümü",
    badge: "Tam Hizmet",
    price: "Özel Teklif",
    period: "şirkete özel",
    description: "Metafonics tarafından anahtar teslim AI asistan kurulumları, özel sesli AI ajanları ve tam uyumluluk.",
    isPopular: false,
    features: [
      "AI READY BUSINESS Kurumsal Sertifikasyonu",
      "Özel Sesli ve Yazılı AI Ajanı Geliştirme",
      "CRM, ERP ve E-Ticaret Derin Entegrasyonu",
      "Çoklu Şube / Çoklu Marka Rozet Lisanslaması",
      "Öncelikli SLA ve Özel Mühendislik Desteği",
      "Aylık AEO ve Satış Dönüşüm Raporlaması",
    ],
    ctaText: "Uzmanla Görüşün",
    ctaHref: "#iletisim",
  },
];
