import { CertificateRecord } from "@/types/certificate";

export const sampleCertificates: CertificateRecord[] = [
  {
    id: "ARB-2025-0001",
    businessName: "AI Ready Business Hub",
    domain: "aireadybusiness.ai",
    issueDate: "15 Ocak 2025",
    expiryDate: "15 Ocak 2026",
    overallScore: 99,
    tier: "VERIFIED",
    stars: 5,
    status: "ACTIVE",
    verifiedBy: "METAFONICS Yapay Zeka Teknolojileri",
    badgeUrl: "https://aireadybusiness.ai/badge/ARB-2025-0001",
    featuresEnabled: [
      "7/24 AI İletişim Entegrasyonu",
      "Otonom Satış ve Lead Dönüşüm Motoru",
      "LLM & AEO (AI Engine) Optimizasyonu",
      "Kriptografik Güvenli Doğrulama",
    ],
    metrics: [
      {
        id: "m-1",
        label: "7/24 AI Müşteri İletişim Hızı",
        score: 99,
        status: "EXCELLENT",
        description: "Ortalama 1.2 saniyede yanıt veriliyor, sıfır cevapsız talep.",
        iconName: "PhoneCall",
      },
      {
        id: "m-2",
        label: "Satış & Dönüşüm Otomasyonu",
        score: 97,
        status: "EXCELLENT",
        description: "Ziyaretçi satın alma adımları otonom akıllı asistan ile yönlendiriliyor.",
        iconName: "TrendingUp",
      },
      {
        id: "m-3",
        label: "AI Arama Motoru Görünürlüğü (AEO)",
        score: 98,
        status: "EXCELLENT",
        description: "ChatGPT, Perplexity ve Claude aramalarında 1. sıra tavsiye uyumu.",
        iconName: "Sparkles",
      },
      {
        id: "m-4",
        label: "Veri Gizliliği & Güvenlik Standartları",
        score: 100,
        status: "EXCELLENT",
        description: "KVKK ve GDPR tam uyumlu yapay zeka veri koruma katmanı.",
        iconName: "ShieldCheck",
      },
    ],
  },
  {
    id: "ARB-2025-8842",
    businessName: "Novasphere Teknoloji Ltd.",
    domain: "novasphere.com",
    issueDate: "02 Şubat 2025",
    expiryDate: "02 Şubat 2026",
    overallScore: 96,
    tier: "VERIFIED",
    stars: 5,
    status: "ACTIVE",
    verifiedBy: "METAFONICS Yapay Zeka Teknolojileri",
    badgeUrl: "https://aireadybusiness.ai/badge/ARB-2025-8842",
    featuresEnabled: [
      "7/24 Çok Dilli Sesli AI",
      "AEO Arama Optimizasyonu",
      "Dinamik CRM Entegrasyonu",
    ],
    metrics: [
      {
        id: "m-1",
        label: "7/24 AI İletişim",
        score: 95,
        status: "EXCELLENT",
        description: "Yapay zeka müşteri danışmanı aktif ve öğrenen modda.",
        iconName: "PhoneCall",
      },
      {
        id: "m-2",
        label: "Satış Optimizasyonu",
        score: 94,
        status: "EXCELLENT",
        description: "Sepet kurtarma ve teklif süreçleri otonom.",
        iconName: "TrendingUp",
      },
      {
        id: "m-3",
        label: "AI Görünürlüğü",
        score: 98,
        status: "EXCELLENT",
        description: "LLM taramalarında onaylı marka kimliği.",
        iconName: "Sparkles",
      },
    ],
  },
];
